Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -126,11 +126,23 @@ jobs:
           echo "Cloning latest repo..."
           rm -rf one_meristem_app || true
           git clone https://${{ secrets.GH_PAT }}@github.com/${{ env.REPO_NAME }}.git
+          echo "Cloning completed..."
 
-          echo "Checking directory..."
+          cd one_meristem_app
+
+          echo "Checking out target branch..."
+          git fetch origin dev_env
+          git checkout -b dev_env origin/dev_env || { echo "Branch checkout failed."; exit 1; }
+          
+          echo "Switched to 'dev_env' branch."
+          echo "Listing folders..."
           ls -l
-          echo "Changing directory..."
-          cd one_meristem_app/${{ env.SERVICES_DIR }} || { echo "Backend folder not found. Check repo structure."; exit 1; }
+          
+          # -----------------------------
+          # Enter the backend folder
+          # -----------------------------
+          echo "Changing into backend directory..."
+          cd backend || { echo "Backend folder not found. Check repo structure."; exit 1; }
 
           # -----------------------------
           # Backup current Docker state
