Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -130,7 +130,7 @@ jobs:
           echo "Checking directory..."
           ls -l
           echo "Changing directory..."
-          cd one_meristem_app/backend || { echo "Backend folder not found. Check repo structure."; exit 1; }
+          cd backend || { echo "Backend folder not found. Check repo structure."; exit 1; }
 
           # -----------------------------
           # Backup current Docker state
